#!/bin/sh

tmpf=/tmp/qwfreQtmpcp
#files=`find src -name \*.py`
files=$*

for i in $files; do
 echo -n "adding copyright to $i... "
 cat templates/copying >$tmpf
 cat $i | sed '/^#[\!~]/d' | sed '/^#\ \-\*\-/d' >>$tmpf
 cat $tmpf >$i
 rm $tmpf
 echo done
done
